// demo/Captcha.tsx
import React, { useState, useEffect, useRef } from 'react';

// API Configuration
const API_BASE = 'http://localhost:3001/api';

// Types
interface CaptchaChallenge {
  id: string;
  targetName: string;
  images: string[];
}

interface TracePoint {
  x: number;
  y: number;
  t: number;
}

export const BangCaptcha: React.FC<{
  onSuccess?: (token: string) => void;
  onFail?: (msg: string) => void;
}> = ({ onSuccess, onFail }) => {
  const [challenge, setChallenge] = useState<CaptchaChallenge | null>(null);
  const [selectedIndexes, setSelectedIndexes] = useState<number[]>([]);
  const [loading, setLoading] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  
  // Track mouse movements for bot prevention
  const traceData = useRef<TracePoint[]>([]);
  const captchaRef = useRef<HTMLDivElement>(null);

  const fetchCaptcha = async () => {
    try {
      setLoading(true);
      setErrorMsg('');
      setSelectedIndexes([]);
      traceData.current = [];
      
      const response = await fetch(`${API_BASE}/captcha`);
      if (!response.ok) throw new Error('Failed to fetch captcha');
      
      const data = await response.json();
      setChallenge(data);
    } catch (error) {
      console.error(error);
      setErrorMsg('验证码加载失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCaptcha();
  }, []);

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!captchaRef.current) return;
    const rect = captchaRef.current.getBoundingClientRect();
    traceData.current.push({
      x: Math.round(e.clientX - rect.left),
      y: Math.round(e.clientY - rect.top),
      t: Date.now()
    });
  };

  const toggleSelect = (index: number) => {
    setSelectedIndexes(prev => 
      prev.includes(index)
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  const handleVerify = async () => {
    if (!challenge || selectedIndexes.length === 0) return;
    
    try {
      setVerifying(true);
      setErrorMsg('');
      
      // Format trace data to match backend [timestamp, x, y] format
      const formattedTrace = traceData.current.map(p => [p.t, p.x, p.y]);
      
      const response = await fetch(`${API_BASE}/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: challenge.id,
          selectedIndexes,
          traceData: formattedTrace,
          // startTime is ignored by backend now but we keep it for API compatibility
          startTime: traceData.current[0]?.t || Date.now()
        })
      });
      
      const result = await response.json();
      
      if (result.success) {
        // Typically you'd pass some token back
        onSuccess?.('verification_passed_token_here');
      } else {
        setErrorMsg(result.message || '验证失败');
        onFail?.(result.message);
        // Refresh captcha on fail
        setTimeout(fetchCaptcha, 1000);
      }
    } catch (error) {
      console.error(error);
      setErrorMsg('网络请求失败');
    } finally {
      setVerifying(false);
    }
  };

  if (loading && !challenge) {
    return <div style={styles.container}>加载中...</div>;
  }

  return (
    <div style={styles.container} ref={captchaRef} onMouseMove={handleMouseMove}>
      <div style={styles.header}>
        <div style={styles.title}>请选出所有包含</div>
        <div style={styles.target}>{challenge?.targetName}</div>
        <div style={styles.subtitle}>的图片</div>
      </div>
      
      {errorMsg && <div style={styles.error}>{errorMsg}</div>}
      
      <div style={styles.grid}>
        {challenge?.images.map((imgUrl, index) => {
          const isSelected = selectedIndexes.includes(index);
          return (
            <div 
              key={index} 
              style={{
                ...styles.imageWrapper,
                border: isSelected ? '3px solid #1890ff' : '3px solid transparent'
              }}
              onClick={() => toggleSelect(index)}
            >
              <img 
                src={imgUrl} 
                alt={`captcha-${index}`} 
                style={styles.image} 
                draggable={false}
              />
              {isSelected && (
                <div style={styles.checkmark}>
                  <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
              )}
            </div>
          );
        })}
      </div>
      
      <div style={styles.footer}>
        <button 
          style={styles.refreshBtn} 
          onClick={fetchCaptcha} 
          disabled={loading || verifying}
        >
          刷新
        </button>
        <button 
          style={{
            ...styles.verifyBtn,
            opacity: selectedIndexes.length === 0 || verifying ? 0.5 : 1
          }} 
          onClick={handleVerify}
          disabled={selectedIndexes.length === 0 || verifying}
        >
          {verifying ? '验证中...' : '确认'}
        </button>
      </div>
    </div>
  );
};

// Inline styles for zero-dependency demo
const styles = {
  container: {
    width: '320px',
    backgroundColor: '#fff',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    padding: '16px',
    fontFamily: 'sans-serif',
    boxSizing: 'border-box' as const,
  },
  header: {
    marginBottom: '16px',
  },
  title: {
    fontSize: '14px',
    color: '#333',
  },
  target: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1890ff',
    margin: '4px 0',
  },
  subtitle: {
    fontSize: '12px',
    color: '#666',
  },
  error: {
    color: '#ff4d4f',
    fontSize: '12px',
    marginBottom: '8px',
    padding: '4px 8px',
    backgroundColor: '#fff2f0',
    borderRadius: '4px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '4px',
    marginBottom: '16px',
  },
  imageWrapper: {
    position: 'relative' as const,
    cursor: 'pointer',
    borderRadius: '4px',
    overflow: 'hidden',
    aspectRatio: '1',
    boxSizing: 'border-box' as const,
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
  },
  checkmark: {
    position: 'absolute' as const,
    top: '4px',
    right: '4px',
    backgroundColor: '#1890ff',
    color: '#fff',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  refreshBtn: {
    background: 'none',
    border: 'none',
    color: '#666',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px 8px',
  },
  verifyBtn: {
    backgroundColor: '#1890ff',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    padding: '8px 24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 'bold',
  }
};

export default BangCaptcha;

// demo/Captcha.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { CaptchaChallenge, CaptchaVerifyRequest, CaptchaVerifyResponse, TracePoint } from '../types';

const API_BASE = 'http://localhost:3001';

const challenge = ref<CaptchaChallenge | null>(null);
const selectedIndexes = ref<number[]>([]);
const message = ref<string>('');
const isSuccess = ref<boolean>(false);
const loading = ref<boolean>(false);

// 行为分析数据
const traceData = ref<TracePoint[]>([]);
const startTime = ref<number>(0);

const fetchCaptcha = async () => {
  loading.value = true;
  message.value = '';
  isSuccess.value = false;
  selectedIndexes.value = [];
  traceData.value = []; // 重置轨迹
  
  try {
    const res = await fetch(`${API_BASE}/api/captcha`);
    if (!res.ok) throw new Error('Network response was not ok');
    const data = await res.json();
    challenge.value = data;
    startTime.value = Date.now(); // 记录开始时间
  } catch (error) {
    console.error('Failed to fetch captcha:', error);
    message.value = '加载验证码失败';
  } finally {
    loading.value = false;
  }
};

const handleMouseMove = (e: MouseEvent) => {
  // 每 50ms 记录一次，或者简单地每移动一点就记录
  // 这里为了演示简单，直接记录所有点，生产环境最好抽样
  if (!challenge.value || isSuccess.value) return;
  
  // 限制轨迹数组大小，防止内存溢出
  if (traceData.value.length > 500) return;

  traceData.value.push([Date.now(), e.clientX, e.clientY]);
};

const toggleSelect = (index: number) => {
  if (selectedIndexes.value.includes(index)) {
    selectedIndexes.value = selectedIndexes.value.filter(i => i !== index);
  } else {
    selectedIndexes.value.push(index);
  }
};

const verifyCaptcha = async () => {
  if (!challenge.value) return;
  
  loading.value = true;
  try {
    const body: CaptchaVerifyRequest = {
      id: challenge.value.id,
      selectedIndexes: selectedIndexes.value,
      traceData: traceData.value,
      startTime: startTime.value
    };

    const res = await fetch(`${API_BASE}/api/verify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
    });
    
    const data: CaptchaVerifyResponse = await res.json();
    
    if (data.success) {
      isSuccess.value = true;
      const timeSec = data.duration ? (data.duration / 1000).toFixed(2) : '0';
      message.value = `${data.message} (耗时: ${timeSec}s)`;
    } else {
      isSuccess.value = false;
      message.value = data.message;
      // 失败后延迟刷新
      setTimeout(() => {
        if (!isSuccess.value) fetchCaptcha();
      }, 1500);
    }
  } catch (error) {
    console.error('Verification failed:', error);
    message.value = '验证请求出错';
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchCaptcha();
});
</script>

<template>
  <div class="captcha-container" @mousemove="handleMouseMove">
    <div v-if="loading && !challenge" class="loading">加载中...</div>
    
    <div v-else-if="challenge" class="captcha-box">
      <div class="header">
        <p>请点击所有的</p>
        <h2>{{ challenge.targetName }}</h2>
      </div>
      
      <div class="grid">
        <div 
          v-for="(img, index) in challenge.images" 
          :key="index"
          class="grid-item"
          @click="toggleSelect(index)"
        >
          <img :src="img" alt="captcha part" />
          <div v-if="selectedIndexes.includes(index)" class="overlay">
            <div class="checkmark">✓</div>
          </div>
        </div>
      </div>
      
      <div class="actions">
        <button @click="fetchCaptcha" class="refresh-btn">刷新</button>
        <button @click="verifyCaptcha" class="verify-btn" :disabled="loading">
          {{ loading ? '验证中...' : '提交' }}
        </button>
      </div>

      <div v-if="message" :class="['message', isSuccess ? 'success' : 'error']">
        {{ message }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.captcha-container {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 300px;
}

.captcha-box {
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  padding: 16px;
  max-width: 400px;
  width: 100%;
}

.header {
  background: #4285f4;
  color: white;
  padding: 16px;
  margin: -16px -16px 16px -16px;
  border-radius: 8px 8px 0 0;
  text-align: left;
}

.header p {
  margin: 0;
  font-size: 14px;
}

.header h2 {
  margin: 4px 0 0 0;
  font-size: 24px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 4px;
  margin-bottom: 16px;
}

.grid-item {
  position: relative;
  cursor: pointer;
  aspect-ratio: 1; /* 正方形 */
  overflow: hidden;
}

.grid-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(66, 133, 244, 0.3); /* Google Blue tint */
  display: flex;
  align-items: center;
  justify-content: center;
  border: 4px solid #4285f4;
  box-sizing: border-box;
}

.checkmark {
  background: #4285f4;
  color: white;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  position: absolute;
  top: 4px;
  left: 4px;
  font-size: 14px;
}

.actions {
  display: flex;
  justify-content: space-between;
  gap: 12px;
}

button {
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
  font-weight: bold;
  transition: background 0.2s;
}

.refresh-btn {
  background: #f1f3f4;
  color: #555;
}

.refresh-btn:hover {
  background: #e0e0e0;
}

.verify-btn {
  background: #4285f4;
  color: white;
  flex-grow: 1;
}

.verify-btn:hover {
  background: #3367d6;
}

.verify-btn:disabled {
  background: #a0c3ff;
  cursor: not-allowed;
}

.message {
  margin-top: 12px;
  padding: 8px;
  border-radius: 4px;
  text-align: center;
  font-weight: bold;
}

.success {
  background: #e6f4ea;
  color: #137333;
}

.error {
  background: #fce8e6;
  color: #c5221f;
}
</style>
